# print("锄禾日当午\\汗滴禾下土\n谁知盘中餐\'粒粒皆辛苦\t举头望明月\"低头思故乡")
# print(r"锄禾日当午\\汗滴禾下土\n谁知盘中餐\'粒粒皆辛苦\t举头望明月\"低头思故乡")


str1=" jsdHaadfAf1332wFjd563112 "
print(str1)
print(len(str1))
print(str1.count("2"))
print(str1.index("w"))
print(str1.find("o"))
print(str1.startswith("s"))
print(id(str1))
print(str1.replace("a","c"))
print(str1.count("a"))
print(id(str1))
list1=str1.split('f')
print(list1)
# str2="%".join(list1)
# print(str2)
print("%".join(list1))
print(str1.strip())
print(str1)
print(str1.isspace())
str3 = str1.upper()
print(str3)
str4 = (str3.lower())
print(str4)
print(str1.center(30,"#"))
print(str1.ljust(30,"#"))
print(str1.rjust(30,"#"))